[build]
  publish = "."                    # si tes pages HTML sont dans la racine. 
                                   # Sinon, mets le chemin (ex. "public").
  functions = "netlify/functions"  # indique le dossier où sont tes fonctions.
